#!/usr/bin/env python

pp = None
cc = None

def startup():
    import atexit
    import os
    import pprint
    import readline
    import rlcompleter
    import sys

    global pp, cc
    pp = lambda x=None: pprint.PrettyPrinter(indent=4).pprint(x)
    cc = lambda: sys.stdout.write(chr(0x1b) + 'c')

    readline.parse_and_bind('tab: complete')
    histfile = os.path.join(os.environ['HOME'], '.python_history')
    try:
        readline.read_history_file(histfile)
    except IOError:
        pass

    atexit.register(readline.write_history_file, histfile)

startup()
del startup
