[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "ty"]

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }
